### ISSUE TITLE
hadoop Skript im LKIT produziert störende logging Ausgabe

### ISSUE THREAD

**Issue by zirpins** [zirpins/bdelab#3]
jeder hadoop Aufruf führt zu folgendem prefix:

Picked up _JAVA_OPTIONS: -Dsun.security.jgss.native=true -Dsun.security.jgss.lib=/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 -Djavax.security.auth.useSubjectCredsOnly=false -Dhttp.auth.preference=kerberos -Djava.security.auth.login.config=~/login.conf -Dhttps.proxyHost=proxyads.hs-karlsruhe.de -Dhttps.proxyPort=8080

Diese Ausgabe sollte im Normalfall nicht erfolgen.

**Comment by smirking-marsupial** [comment]
Erledigt
